// Generated by gencpp from file ros_gui/motionMSG.msg
// DO NOT EDIT!


#ifndef ROS_GUI_MESSAGE_MOTIONMSG_H
#define ROS_GUI_MESSAGE_MOTIONMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_gui
{
template <class ContainerAllocator>
struct motionMSG_
{
  typedef motionMSG_<ContainerAllocator> Type;

  motionMSG_()
    : doMotion(false)  {
    }
  motionMSG_(const ContainerAllocator& _alloc)
    : doMotion(false)  {
  (void)_alloc;
    }



   typedef uint8_t _doMotion_type;
  _doMotion_type doMotion;





  typedef boost::shared_ptr< ::ros_gui::motionMSG_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_gui::motionMSG_<ContainerAllocator> const> ConstPtr;

}; // struct motionMSG_

typedef ::ros_gui::motionMSG_<std::allocator<void> > motionMSG;

typedef boost::shared_ptr< ::ros_gui::motionMSG > motionMSGPtr;
typedef boost::shared_ptr< ::ros_gui::motionMSG const> motionMSGConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_gui::motionMSG_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_gui::motionMSG_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_gui

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ros_gui': ['/home/lauro199471/catkin_ws/src/ros_gui/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_gui::motionMSG_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_gui::motionMSG_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_gui::motionMSG_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_gui::motionMSG_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_gui::motionMSG_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_gui::motionMSG_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_gui::motionMSG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "07137fc31bb47aafc1cdc6ca1d316779";
  }

  static const char* value(const ::ros_gui::motionMSG_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x07137fc31bb47aafULL;
  static const uint64_t static_value2 = 0xc1cdc6ca1d316779ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_gui::motionMSG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_gui/motionMSG";
  }

  static const char* value(const ::ros_gui::motionMSG_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_gui::motionMSG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool doMotion\n\
";
  }

  static const char* value(const ::ros_gui::motionMSG_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_gui::motionMSG_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.doMotion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motionMSG_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_gui::motionMSG_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_gui::motionMSG_<ContainerAllocator>& v)
  {
    s << indent << "doMotion: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.doMotion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_GUI_MESSAGE_MOTIONMSG_H
